### ISSUE TITLE
Install fails on vcflib (but succeeds on second attempt)

### ISSUE THREAD

**Issue by kdaily** [chapmanb/cloudbiolinux#194]
This happened when running:
```
python bcbio_nextgen_install.py /usr/local/share/bcbio --sudo --tooldir=/usr/local --genomes GRCh37 --aligners bwa --aligners bowtie2
```

```
[localhost] local: export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/usr/local/lib/perl5:${PERL5LIB} && /usr/local/bin/brew install --env=inherit   vcflib

Warning: local() encountered an error (return code 1) while executing 'export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/usr/local/lib/perl5:${PERL5LIB} && /usr/local/bin/brew install --env=inherit   vcflib'

Traceback (most recent call last):
  File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 222, in _install_pkg_latest
    cmd.replace("brew install", "brew install -v"))
ValueError: Failed to install brew formula: vcflib
To debug, please try re-running the install command with verbose output:
export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/usr/local/lib/perl5:${PERL5LIB} && /usr/local/bin/brew install -v --env=inherit   vcflib
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 261, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--sudo', '--tooldir=/usr/local', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
```

Following the instructions and re-running the install command was successful!

```
root@ip-172-31-8-91:~# export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/usr/local/lib/perl5:${PERL5LIB} && /usr/local/bin/brew install -v --env=inherit   vcflib
==> Installing vcflib from homebrew/homebrew-science
==> Cloning https://github.com/ekg/vcflib.git
...
...
==> Summary
/usr/local/Cellar/vcflib/20150314: 101 files, 125M, built in 4.2 minutes
```

However, I would like this to be unattended. Any suggestions? Thanks!

**Comment by chapmanb** [comment]
Kenneth;
Sorry, that is unexpected. The manual re-run doesn't do anything different that the original build so I'm not sure why you're annoyingly seeing a failure during the automated install. A couple of thoughts:

- Is this reproducible on multiple runs? I like full automation but some of this can fail due to network errors as it tries to pull or clone things from GitHub.
- What type of AWS instance are you building with? The automated fabric install does some parallelization so it might be overwhelming a smaller instance type.

I'll try to reproduce here to debug further but haven't been able to make it fail yet. Hope this helps some.

**Comment by kdaily** [comment]
I will try again! It took a while to run up to that point and I had to
switch to another task. I was using an m3.medium, so I can go larger too.

**Comment by kdaily** [comment]
I got it to fail again! I'm starting from starcluster-base-ubuntu-12.04-x86_64 (ami-765b3e1f). I tried again on an m3.medium, and also on an m3.xlarge.

**Comment by kdaily** [comment]
I forked and used my own flavor to fix another issue (I required `R 3.1` not `3.2`, so I removed `r` and `r-libs` from the config. Strangely, this did not give me an error with `vcflib`. It gave a couple errors at the end, but not sure that they're significant (seems like cleanup):

```
[localhost] local: export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/usr/local/lib/perl5:${PERL5LIB} && /usr/local/bin/brew install --env=inherit   tophat-binary
[localhost] local: /usr/local/bin/brew link --overwrite tophat-binary
Warning: Already linked: /usr/local/Cellar/tophat-binary/2.0.14
To relink: brew unlink tophat-binary && brew link tophat-binary
[localhost] local: /usr/local/bin/brew info cmake
[localhost] local: /usr/local/bin/brew info pkg-config
[localhost] local: export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/usr/local/lib/perl5:${PERL5LIB} && /usr/local/bin/brew install --env=inherit   s3gof3r
[localhost] local: /usr/local/bin/brew link --overwrite s3gof3r
Warning: Already linked: /usr/local/Cellar/s3gof3r/0.4.8
To relink: brew unlink s3gof3r && brew link s3gof3r
[localhost] local: /usr/local/bin/brew info cpanminus
[localhost] local: /usr/local/bin/brew unlink pkg-config
Unlinking /usr/local/Cellar/pkg-config/0.28... 4 symlinks removed
[localhost] local: /usr/local/bin/brew unlink openssl
Error: No such keg: /usr/local/Cellar/openssl

Warning: local() encountered an error (return code 1) while executing '/usr/local/bin/brew unlink openssl'

[localhost] local: /usr/local/bin/brew unlink curl
Error: No such keg: /usr/local/Cellar/curl

Warning: local() encountered an error (return code 1) while executing '/usr/local/bin/brew unlink curl'

[localhost] local: /usr/local/bin/brew unlink cmake
Unlinking /usr/local/Cellar/cmake/3.2.2... 8 symlinks removed
DBG [config.py]: Using config file /root/src/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal_nor/main.yaml
INFO: Meta-package information from /root/src/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal_nor/main.yaml
- Packages: minimal,libraries,perl,python,java,ruby,bio_nextgen
- Libraries: 
INFO: Cleaning up space from package builds
[localhost] local: sudo http_proxy=$http_proxy https_proxy=$https_proxy  bash -c "rm -rf .cpanm"
[localhost] local: sudo http_proxy=$http_proxy https_proxy=$https_proxy  bash -c "rm -f /var/crash/*"
[localhost] local: rm -f ~/*.dot
[localhost] local: rm -f ~/*.log
INFO: Config end time: 2015-06-05 23:30:47.235798; duration: 0:07:04.052517
```

**Comment by chapmanb** [comment]
Kenneth;
It did finish cleanly with your final run. Those messages are nothing to worry about -- it unlinks some brew packages which are better provided by the filesystem if they exist. I silenced the messages so they won't confuse anyone in the future.

On your bigger issue of run failures, I'm still stumped. Your changed formula shouldn't have any influence on this. If it still fails on xlarge runs my guess it that it runs into issues cloning the repository. vcflib uses a recursive clone from GitHub with submodules so that might be failing intermittently. I'll keep trying to reproduce/debug from my side, but wish I had something better to suggest right now.

**Comment by kdaily** [comment]
Not getting this anymore!
