### ISSUE TITLE
Crashes on freenx scripts

### ISSUE THREAD

**Issue by kdaily** [chapmanb/cloudbiolinux#202]
I get the following when installing `ngs_pipeline_minimal` on a CentOS 6.6 EC2 AMI (I changed the `config/fabricrc.txt` to have `is_ec2_image = true`):

```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/usr/lib/python2.6/site-packages/fabric/tasks.py", line 387, in execute
    multiprocessing
  File "/usr/lib/python2.6/site-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib64/python2.6/contextlib.py", line 113, in nested
    yield vars
  File "/usr/lib/python2.6/site-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/root/src/cloudbiolinux/fabfile.py", line 77, in install_biolinux
    _perform_install(target, flavor)
  File "/root/src/cloudbiolinux/fabfile.py", line 126, in _perform_install
    _freenx_scripts(self.env)
NameError: global name 'self' is not defined
```

**Comment by kdaily** [comment]
I think I didn't actually want that `is_ec2_image = true`; it exited gracefully after setting to false...

**Comment by chapmanb** [comment]
Kenneth;
Thanks for the heads up on the issue. You're right that you don't want `is_ec2_image=true`, but I also fixed the underlying copy/paste bugs causing the error. Thanks again.
