### ISSUE TITLE
not getting conda packages in ngs_pipeline_minimal

### ISSUE THREAD

**Issue by kdaily** [chapmanb/cloudbiolinux#210]
I'm trying to use `ngs_pipeline_minimal` but not getting any of the packages in the conda-based package list. Advice would be appreciated!

**Comment by chapmanb** [comment]
Kenneth;
Sorry about the issues. Can you provide a bit more details about how you ran cloudbiolinux? I'd be happy to try and debug the issue. Thanks much.

**Comment by kdaily** [comment]
I'm on a CentOS 6.7 EC2. I'm using `module` to manage multiple versions of `Python`. I ran (as root):

```
git clone git://github.com/chapmanb/cloudbiolinux.git
cd cloudbiolinux

module load python/2.7.10
fab -f fabfile.py -H localhost install_biolinux:flavor=ngs_pipeline_minimal
```

It finishes cleanly, but never installs anything from `ngs_pipeline_minimal/packages-conda.yaml`.

Also, I tried:

```
fab -f fabfile.py -H localhost install_biolinux:target=conda,flavor=ngs_pipeline_minimal
```

Which did not work either:


```
fab -f fabfile.py -H localhost install_biolinux:target=conda,flavor=ngs_pipeline_minimal
[localhost] Executing task 'install_biolinux'
INFO: Config start time: 2015-11-24 22:14:50.461066
INFO: <cloudbio.flavor.Flavor instance at 0x7f71dad7cb90>
INFO: This is a ngs_pipeline_minimal flavor
INFO: Reading default fabricrc.txt
DBG [config.py]: Using config file /root/src/cloudbiolinux/cloudbio/../config/fabricrc.txt
INFO: Distribution __auto__
INFO: Get local environment
INFO: CentOS setup
DBG [distribution.py]: Checking target distribution centos
DBG [distribution.py]: Unknown target distro
DBG [distribution.py]: NixPkgs: Ignored
[localhost] local: echo $HOME
[localhost] local: uname -m
INFO: Now, testing connection to host...
INFO: Connection to host appears to work!
DBG [utils.py]: Expand paths
DBG [fabfile.py]: Target is 'conda'
DBG [fabfile.py]: Flavor is 'ngs_pipeline_minimal'
DBG [config.py]: Using config file /root/src/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/main.yaml
INFO: Meta-package information from /root/src/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/main.yaml
- Packages: minimal,libraries,perl,python,java,r,ruby,bio_nextgen
- Libraries: r-libs
DBG [config.py]: Using config file /root/src/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/main.yaml
INFO: Meta-package information from /root/src/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/main.yaml
- Packages: minimal,libraries,perl,python,java,r,ruby,bio_nextgen
- Libraries: r-libs
INFO: Config end time: 2015-11-24 22:14:50.527322; duration: 0:00:00.066256
```

I also tried `pip install conda` but get a warning that this is not the proper way to install; however if I do install Miniconda manually, it also installs it's own python and wants to put it on my PATH!

**Comment by kdaily** [comment]
Moving all the packages out of `to_remove` and into another block in `ngs_pipeline_minimal/packages-homebrew.yaml` installs them properly.

**Comment by kdaily** [comment]
Maybe I interpreted the output wrong. After moving the packages out of `to_remove` and removing some currently broken ones (`lumpy-sv` for one; submitted an issue at that repo) it DOES get to the conda packages. However, I get this now:

```
DBG [config.py]: Using config file /root/src/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml
INFO: Reading /root/src/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml
DBG [shared.py]: Packages to install: bamtools,bcbio-prioritize,bcftools,bedtools=2.24.0,bio-vcf,biobambam,bowtie2,bwa,cnvkit,cufflinks,cutadapt,fastqc,freebayes=0.9.21.26,gatk-framework,glpk,grabix,hisat2,hmmlearn,htseq,lumpy-sv,manta,metasv,moreutils,optitype,parallel,pbgzip,phylowgs,pyloh,pytabix,pythonpy,razers3,sailfish,sambamba,samblaster,samtools,scalpel,seqtk,simple_sv_annotation,snpeff,star,stringtie,subread,svtyper,tophat,ucsc-bedgraphtobigwig,ucsc-bedtobigbed,ucsc-bigbedinfo,ucsc-bigbedsummary,ucsc-bigbedtobed,ucsc-bigwiginfo,ucsc-bigwigsummary,ucsc-bigwigtobedgraph,ucsc-bigwigtowig,ucsc-fatotwobit,ucsc-gtftogenepred,ucsc-liftover,ucsc-wigtobigwig,vardict,vardict-java,varscan,vawk,vcflib,vt,wham,bioconductor-annotate,bioconductor-biocinstaller,bioconductor-biostrings,bioconductor-biovizbase,bioconductor-deseq2,bioconductor-genomicranges,bioconductor-iranges,bioconductor-limma,bioconductor-rtracklayer,r,r-colorspace,r-devtools,r-dplyr,r-e1071,r-locfit,r-magrittr,r-plyr,r-rcolorbrewer,r-rcpp,r-rcpparmadillo,r-rcurl,r-rgl,r-rsqlite,r-snow,r-stringi,r-xtable
[localhost] local: /usr/local/anaconda/bin/conda info --json
[localhost] local: /usr/local/anaconda/bin/conda install -y -c bcbio -c bioconda -c r bamtools bcbio-prioritize bcftools bedtools=2.24.0 bio-vcf biobambam bowtie2 bwa cnvkit cufflinks cutadapt fastqc freebayes=0.9.21.26 gatk-framework glpk grabix hisat2 hmmlearn htseq lumpy-sv manta metasv moreutils optitype parallel pbgzip phylowgs pyloh pytabix pythonpy razers3 sailfish sambamba samblaster samtools scalpel seqtk simple_sv_annotation snpeff star stringtie subread svtyper tophat ucsc-bedgraphtobigwig ucsc-bedtobigbed ucsc-bigbedinfo ucsc-bigbedsummary ucsc-bigbedtobed ucsc-bigwiginfo ucsc-bigwigsummary ucsc-bigwigtobedgraph ucsc-bigwigtowig ucsc-fatotwobit ucsc-gtftogenepred ucsc-liftover ucsc-wigtobigwig vardict vardict-java varscan vawk vcflib vt wham bioconductor-annotate bioconductor-biocinstaller bioconductor-biostrings bioconductor-biovizbase bioconductor-deseq2 bioconductor-genomicranges bioconductor-iranges bioconductor-limma bioconductor-rtracklayer r r-colorspace r-devtools r-dplyr r-e1071 r-locfit r-magrittr r-plyr r-rcolorbrewer r-rcpp r-rcpparmadillo r-rcurl r-rgl r-rsqlite r-snow r-stringi r-xtable
usage: conda [-h] [-V] command ...
conda: error: unrecognized arguments: -y

Fatal error: local() encountered an error (return code 2) while executing '/usr/local/anaconda/bin/conda install -y -c bcbio -c bioconda -c r bamtools bcbio-prioritize bcftools bedtools=2.24.0 bio-vcf biobambam bowtie2 bwa cnvkit cufflinks cutadapt fastqc freebayes=0.9.21.26 gatk-framework glpk grabix hisat2 hmmlearn htseq lumpy-sv manta metasv moreutils optitype parallel pbgzip phylowgs pyloh pytabix pythonpy razers3 sailfish sambamba samblaster samtools scalpel seqtk simple_sv_annotation snpeff star stringtie subread svtyper tophat ucsc-bedgraphtobigwig ucsc-bedtobigbed ucsc-bigbedinfo ucsc-bigbedsummary ucsc-bigbedtobed ucsc-bigwiginfo ucsc-bigwigsummary ucsc-bigwigtobedgraph ucsc-bigwigtowig ucsc-fatotwobit ucsc-gtftogenepred ucsc-liftover ucsc-wigtobigwig vardict vardict-java varscan vawk vcflib vt wham bioconductor-annotate bioconductor-biocinstaller bioconductor-biostrings bioconductor-biovizbase bioconductor-deseq2 bioconductor-genomicranges bioconductor-iranges bioconductor-limma bioconductor-rtracklayer r r-colorspace r-devtools r-dplyr r-e1071 r-locfit r-magrittr r-plyr r-rcolorbrewer r-rcpp r-rcpparmadillo r-rcurl r-rgl r-rsqlite r-snow r-stringi r-xtable'

Aborting.
```

**Comment by chapmanb** [comment]
Kenneth;
Thanks for the additional details. This helps a lot for offering better advice:

- For the homebrew recipes, the ones listed under `to_remove` are not supposed to be installed. These migrated to conda recipes, so the `to_remove` tag removes the corresponding brew formula if it was previously installed. So, you don't want these installed via brew.
- For the conda build, what version of conda do you have in `/usr/local/anaconda/bin/conda`? If appears to not have the `-y` argument (which prevents asking for confirmation) so might be rather old. The `ngs_pipeline_minimal` flavor is primarily used by the bcbio installer, which does the work installing the up to date conda. If you're looking for an isolated installation of these tools in a clean way you could use the bcbio installer but skip installing any data:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#isolated-installations

with a command like:
```
bcbio_python bcbio_nextgen_install.py --tooldir /path/to/tools/bin --nodata --isolate /path/to/put/anaconda
```
This takes care of managing all the cloudbiolinux machinery for you.

Hope this helps.

**Comment by kdaily** [comment]
Thanks for the suggestions Brad! 

I think it's a problem of the Python environment - I installed Python 2.7 using `altinstall` to an isolated directory, as the system depends on Python 2.6 (for yum). So, I was using `modules` to manage this; but then Conda adds things to the path and breaks the current Python. I'm redoing this with a Python `altinstall` to the system directory and then calling `python2.7` directly everywhere to see if that alleviates my pain!

**Comment by chapmanb** [comment]
Kenneth;
Modules and lots of environmental variables can definitely confuse things. You can end up getting libraries from different installs injected in your path which causes confusing issues. If you use the bcbio approach above that tries to ignore these settings and installs it's own isolated Python to avoid them. Hope this helps sort it out for you.

**Comment by kdaily** [comment]
I'm thinking this is the easiest route. However I'm getting errors with that as well. Maybe this isn't the best place to discuss? If not, I can move the issue elsewhere and close this.

I called:

```
wget https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
python bcbio_nextgen_install.py /opt/bcbio --tooldir=/opt/bcbio --isolate --genomes GRCh37 --aligners bwa --aligners bowtie2
```

Here's what I get:

```
trying URL 'http://bioconductor.org/packages/3.2/bioc/src/contrib/BiocInstaller_1.20.1.tar.gz'
Content type 'application/x-gzip' length 15695 bytes (15 KB)
==================================================
downloaded 15 KB

* installing *source* package ‘BiocInstaller’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Bioconductor version 3.2 (BiocInstaller 1.20.1), ?biocLite for help
* DONE (BiocInstaller)

The downloaded source packages are in
	‘/tmp/RtmpXSwq0N/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Bioconductor version 3.2 (BiocInstaller 1.20.1), ?biocLite for help
'BiocInstaller' updated to version 1.20.1
BioC_mirror: http://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.1), R 3.2.2 (2015-08-14).
Installing package(s) ‘BiocStyle’
trying URL 'http://bioconductor.org/packages/3.2/bioc/src/contrib/BiocStyle_1.8.0.tar.gz'
Content type 'application/x-gzip' length 234673 bytes (229 KB)
==================================================
downloaded 229 KB

* installing *source* package ‘BiocStyle’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (BiocStyle)

The downloaded source packages are in
	‘/tmp/RtmpXSwq0N/downloaded_packages’
Old packages: 'biomaRt', 'Biostrings', 'curl', 'GenomicFeatures', 'IRanges',
  'jsonlite', 'limma', 'MASS', 'Matrix', 'mgcv', 'Rcpp', 'RcppArmadillo',
  'rgl', 'roxygen2', 'S4Vectors', 'stringi', 'xtable'
Error in install.fn(pname) : 
  lazy-load database '/opt/bcbio/anaconda/lib/R/library/BiocInstaller/R/BiocInstaller.rdb' is corrupt
Calls: lapply -> FUN -> install.fn
In addition: Warning message:
In install.fn(pname) : internal error -3 in R_decompress1
Execution halted

Fatal error: local() encountered an error (return code 1) while executing '/opt/bcbio/anaconda/bin/Rscript /root/tmp/cloudbiolinux/install_packages.R'

Aborting.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 275, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 46, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/opt/bcbio', '--isolate', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Kenneth;
Thanks for the report and sorry for the continued problems. It looks like you somehow got a corrupt database of Bioconductor tools. Hopefully you can remove that and bcbio will re-install:
```
rm -f /opt/bcbio/anaconda/lib/R/library/BiocInstaller/R/BiocInstaller.rdb
```
If that doesn't do it (or gives another similar error), try `rm -rf`ing the whole BiocInstaller directory and letting bcbio re-install that for you when restarting. You can re-run the exact same install command and it'll pick up where it left off. Hopefully this moves you further along. Thanks much for the patience.

**Comment by kdaily** [comment]
Huh! I actually fixed it by removing the `BiocInstaller` that was (previously) installed in `/usr/lib64/R/library`...

**Comment by kdaily** [comment]
Oops - was to hasty to say that. Not sure how it went on (as it got to downloading some genome data). I restarted to make sure (as I'll be running this unattended, I hope) and got this:

```
DBG [config.py]: Using config file /root/tmpbcbio-install/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/r-libs.yaml
[localhost] local: echo $HOME
[localhost] local: rm -f /root/tmp/cloudbiolinux/install_packages.R
[localhost] local: touch /root/tmp/cloudbiolinux/install_packages.R
[localhost] local: mkdir -p /opt/bcbio/lib/R/site-library
[localhost] local: chown -R root /opt/bcbio/lib/R/site-library
[localhost] local: echo '
    .libPaths(c("/opt/bcbio/lib/R/site-library"))
    library(methods)
    cran.repos <- getOption("repos")
    cran.repos["CRAN" ] <- "http://cran.fhcrc.org/"
    options(repos=cran.repos)
    source("http://bioconductor.org/biocLite.R")
    ' >> "$(echo /root/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: echo '
    repo.installer <- function(repos, install.fn, pkg_name_fn) {
      
        update.packages(lib.loc="/opt/bcbio/lib/R/site-library", repos=repos, ask=FALSE)
        
      maybe.install <- function(pname) {
        if (!is.null(pkg_name_fn)) {
           pinfo <- pkg_name_fn(pname)
           ipkgs <- installed.packages()[,3][pinfo["pkg"]]
           if (is.na(ipkgs[pinfo["pkg"]]) || pinfo["version"] != ipkgs[pinfo["pkg"]])
             try(install.fn(pinfo["pname"]))
        }
        else if (!(is.element(pname, installed.packages()[,1])))
           install.fn(pname)
      }

    }
    ' >> "$(echo /root/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: echo '
    std.pkgs <- c("cghFLasso", "ggplot2", "gsalib", "gtools", "matrixStats", "rainbow", "WriteXLS")
    std.installer = repo.installer(cran.repos, install.packages, NULL)
    lapply(std.pkgs, std.installer)
    ' >> "$(echo /root/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: echo '
        bioc.pkgs <- c("BiocStyle", "cn.mops", "DEXSeq", "DNAcopy")
        bioc.installer = repo.installer(biocinstallRepos(), biocLite, NULL)
        lapply(bioc.pkgs, bioc.installer)
        ' >> "$(echo /root/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: echo '
        std2.pkgs <- c("PSCBS")
        lapply(std2.pkgs, std.installer)
        ' >> "$(echo /root/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: echo '
        library(devtools)
        github.pkgs <- c("Bioconductor-mirror/BubbleTree@6a85d81;2.1.4")
        get_pkg_name <- function(orig) {
          c(pkg=unlist(strsplit(unlist(strsplit(orig, "/"))[2], "@"))[1],
            version=unlist(strsplit(orig, ";"))[2],
            pname=unlist(strsplit(orig, ";"))[1])
        }
        gh_install <- function(name) {
          install_github(name, upgrade_dependencies=FALSE)
        }
        github_installer = repo.installer(NULL, gh_install, get_pkg_name)
        lapply(github.pkgs, github_installer)
        ' >> "$(echo /root/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: /opt/bcbio/anaconda/bin/Rscript /root/tmp/cloudbiolinux/install_packages.R
Error in get0(hookname, envir = env, inherits = FALSE) : 
  cannot open file '/opt/bcbio/anaconda/lib/R/library/BiocInstaller/R/BiocInstaller.rdb': No such file or directory
Installing package into ‘/opt/bcbio/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'http://bioconductor.org/packages/3.2/bioc/src/contrib/BiocInstaller_1.20.1.tar.gz'
Content type 'application/x-gzip' length 15695 bytes (15 KB)
==================================================
downloaded 15 KB

* installing *source* package ‘BiocInstaller’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Bioconductor version 3.2 (BiocInstaller 1.20.1), ?biocLite for help
* DONE (BiocInstaller)

The downloaded source packages are in
	‘/tmp/RtmpAAx5j2/downloaded_packages’
Error in get0(hookname, envir = env, inherits = FALSE) : 
  cannot open file '/opt/bcbio/anaconda/lib/R/library/BiocInstaller/R/BiocInstaller.rdb': No such file or directory
'biocLite.R' failed to install 'BiocInstaller', use
  'install.packages("BiocInstaller",
  repos="https://bioconductor.org/packages/3.1/bioc")' or
  'install.packages("BiocInstaller",
  repos="http://bioconductor.org/packages/3.1/bioc")'
[[1]]
NULL

[[2]]
NULL

[[3]]
NULL

[[4]]
NULL

[[5]]
NULL

[[6]]
NULL

[[7]]
NULL

Error in contrib.url(repos, type) : 
  could not find function "biocinstallRepos"
Calls: repo.installer ... update.packages -> available.packages -> contrib.url
Execution halted

Fatal error: local() encountered an error (return code 1) while executing '/opt/bcbio/anaconda/bin/Rscript /root/tmp/cloudbiolinux/install_packages.R'

Aborting.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 275, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 46, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/opt/bcbio', '--isolate', '--aligners', 'bwa', '--aligners', 'bowtie2', '--aligners', 'bowtie', '--distribution', 'centos', '--aligners', 'star', '--aligners', 'novoalign']' returned non-zero exit status 1
```

**Comment by kdaily** [comment]
Manually installing `BiocInstaller` and then restarting the bcbio install fixed it.

**Comment by chapmanb** [comment]
Kenneth;
Thanks for following up. I'm glad the manual install got things working. Apologies about the multiple efforts to get it going -- we're gradually migrating over to pre-built conda packages for R tools which should make this easier in the long term but it's still a little hacky right now.

**Comment by kdaily** [comment]
Appreciate your guidance. Thanks again.
