### ISSUE TITLE
Error building setuptools ubuntu

### ISSUE THREAD

**Issue by rchekaluk** [chapmanb/cloudbiolinux#212]
Building on Ubuntu Trusty:

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
```

... yields this error when installing setuptools:

```
[host] run: /usr/local/anaconda/bin/pip install --upgrade setuptools --allow-unverified setuptools --allow-external setuptools
[host] out: Collecting setuptools
[host]] out:   Downloading setuptools-19.4-py2.py3-none-any.whl (471kB)
...
[host] out: Installing collected packages: setuptools
[host] out:   Found existing installation: setuptools 19.2
[host]out:     Uninstalling setuptools-19.2:
[host] out:       Successfully uninstalled setuptools-19.2
[host] out: Successfully installed setuptools
[host] out: Traceback (most recent call last):
[host] out:   File "/usr/local/anaconda/bin/pip", line 6, in <module>
[host] out:     sys.exit(main())
[host] out:   File "/usr/local/anaconda/lib/python2.7/site-packages/pip/__init__.py", line 230, in main
[host] out:     return command.main(cmd_args)
[host] out:   File "/usr/local/anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 248, in main
[host] out:     pip_version_check(session)
[host] out:   File "/usr/local/anaconda/lib/python2.7/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
[host] out:     installed_version = get_installed_version("pip")
[host] out:   File "/usr/local/anaconda/lib/python2.7/site-packages/pip/utils/__init__.py", line 858, in get_installed_version
[host] out:     working_set = pkg_resources.WorkingSet()
[host] out:   File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 629, in __init__
[host] out:     self.add_entry(entry)
[host] out:   File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 685, in add_entry
[host] out:     for dist in find_distributions(entry, True):
[host] out:   File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2075, in find_eggs_in_zip
[host] out:     if metadata.has_metadata('PKG-INFO'):
[host] out:   File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1605, in has_metadata
[host] out:     return self.egg_info and self._has(self._fn(self.egg_info, name))
[host] out:   File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1963, in _has
[host] out:     return zip_path in self.zipinfo or zip_path in self._index()
[host] out:   File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1843, in zipinfo
[host] out:     return self._zip_manifests.load(self.loader.archive)
[host] out:   File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1783, in load
[host] out:     mtime = os.stat(path).st_mtime
[host] out: OSError: [Errno 2] No such file or directory: '/usr/local/anaconda/lib/python2.7/site-packages/setuptools-19.2-py2.7.egg'

Fatal error: run() received nonzero return code 1 while executing!

Requested: /usr/local/anaconda/bin/pip install --upgrade setuptools --allow-unverified setuptools --allow-external setuptools
Executed: /bin/bash -i -c "/usr/local/anaconda/bin/pip install --upgrade setuptools --allow-unverified setuptools --allow-external setuptools"
```

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the problem. It looks like the install is complaining because of updating setuptools in place. What type of install are you working on doing with CloudBioLinux? We're working on migrating the python functionality in CloudBioLinux to use bioconda (https://bioconda.github.io/) which might be a good alternative install path for getting the tools you need for an analysis. Hope this helps some, and happy to provide more specific ideas based on what you need to do.
