### ISSUE TITLE
Error building bx-python Ubuntu

### ISSUE THREAD

**Issue by rchekaluk** [chapmanb/cloudbiolinux#218]
Building on Ubuntu Trusty:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
```
... yields this error when installing bx-python:
```
$ /usr/local/anaconda/bin/pip install --upgrade https://bitbucket.org/james_taylor/bx-python/get/tip.tar.bz2
Collecting https://bitbucket.org/james_taylor/bx-python/get/tip.tar.bz2
  Using cached https://bitbucket.org/james_taylor/bx-python/get/tip.tar.bz2
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.35.tar.gz
    Extracting in /tmp/tmp72C_ib
    Now working in /tmp/tmp72C_ib/distribute-0.6.35
    Building a Distribute egg in /tmp/pip-Ybs2ZO-build
    Traceback (most recent call last):
      File "setup.py", line 45, in <module>
        exec(init_file.read(), d)
      File "<string>", line 8, in <module>
      File "/tmp/tmp72C_ib/distribute-0.6.35/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/tmp/tmp72C_ib/distribute-0.6.35/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/tmp72C_ib/distribute-0.6.35/setuptools/dist.py", line 6, in <module>
        from setuptools.command.install import install
      File "/tmp/tmp72C_ib/distribute-0.6.35/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/tmp/tmp72C_ib/distribute-0.6.35/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/tmp/tmp72C_ib/distribute-0.6.35/pkg_resources.py", line 2825, in <module>
        add_activation_listener(lambda dist: dist.activate())
      File "/tmp/tmp72C_ib/distribute-0.6.35/pkg_resources.py", line 710, in subscribe
        callback(dist)
      File "/tmp/tmp72C_ib/distribute-0.6.35/pkg_resources.py", line 2825, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/tmp/tmp72C_ib/distribute-0.6.35/pkg_resources.py", line 2257, in activate
        self.insert_on(path)
      File "/tmp/tmp72C_ib/distribute-0.6.35/pkg_resources.py", line 2358, in insert_on
        "with distribute. Found one at %s" % str(self.location))
    ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /usr/local/anaconda/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg
    /tmp/pip-Ybs2ZO-build/distribute-0.6.35-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-Ybs2ZO-build/setup.py", line 9, in <module>
        use_setuptools()
      File "distribute_setup.py", line 152, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 132, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "distribute_setup.py", line 123, in _build_egg
        raise IOError('Could not build the egg.')
    IOError: Could not build the egg.
```

The error occurs with both Anaconda 2.0.0 and 2.5.0 (stack trace above):
```
$ python -c "import sys; print sys.version"
2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

$ pip --version
pip 8.1.1 from /usr/local/anaconda/lib/python2.7/site-packages (python 2.7)

$ /usr/local/anaconda/bin/pip --version
pip 8.1.1 from /usr/local/anaconda/lib/python2.7/site-packages (python 2.7)
```

Note that this looks suspiciously similar to https://github.com/chapmanb/cloudbiolinux/commit/77d39aba323fad98fdac47a883748dff049a86bd

**Comment by chapmanb** [comment]
Sorry about the build problem. I'd suggest using conda for the install with the package from bioconda (https://github.com/bioconda/bioconda-recipes):
```
/usr/local/anaconda/bin/conda install -c bioconda bx-python
```
Hope this helps.

**Comment by rchekaluk** [comment]
Sorry, I'd neglected to mention that this results from building a (nearly) stock version of cloudbiolinux. Based on this and previous tickets, am I understanding correctly that cloudbiolinux is in a state of flux and has broken builds ATM?

```
$ fab -H $host -u ubuntu -i $identity_file install_biolinux
...
INFO: Custom install for 'tracer' end time: 2016-04-23 12:53:46.803466; duration: 0:00:06.336533
INFO: Custom install for 'bx-python' start time: 2016-04-23 12:53:46.803635
DBG [fabfile.py]: Importing module cloudbio.custom.python
DBG [fabfile.py]: Looking for custom install function cloudbio.custom.python.install_bx_python

[ec2-54-88-141-236.compute-1.amazonaws.com] run: chmod a+x Tracer_v1.5/bin/tracer
[ec2-54-88-141-236.compute-1.amazonaws.com] sudo: mkdir -p /usr/local/bioinf
[ec2-54-88-141-236.compute-1.amazonaws.com] sudo: rm -rvf /usr/local/bioinf/tracer
[ec2-54-88-141-236.compute-1.amazonaws.com] sudo: mv -f Tracer_v1.5 /usr/local/bioinf/tracer
[ec2-54-88-141-236.compute-1.amazonaws.com] sudo: ln -sf /usr/local/bioinf/tracer/bin/tracer /usr/local/bin/tracer
[ec2-54-88-141-236.compute-1.amazonaws.com] run: rm -rf /home/ubuntu/tmp/cloudbiolinux
[ec2-54-88-141-236.compute-1.amazonaws.com] run: /usr/local/anaconda/bin/python -c 'import bx' 2>&1 | grep -c ImportError | cat
[ec2-54-88-141-236.compute-1.amazonaws.com] out: 1
[ec2-54-88-141-236.compute-1.amazonaws.com] out: 

[ec2-54-88-141-236.compute-1.amazonaws.com] run: /usr/local/anaconda/bin/pip install --upgrade https://bitbucket.org/james_taylor/bx-python/get/tip.tar.bz2
[ec2-54-88-141-236.compute-1.amazonaws.com] out: Collecting https://bitbucket.org/james_taylor/bx-python/get/tip.tar.bz2
[ec2-54-88-141-236.compute-1.amazonaws.com] out:   Downloading https://bitbucket.org/james_taylor/bx-python/get/tip.tar.bz2
[ec2-54-88-141-236.compute-1.amazonaws.com] out: 
[ec2-54-88-141-236.compute-1.amazonaws.com] out:      - 10kB 34.7MB/s
...
[ec2-54-88-141-236.compute-1.amazonaws.com] out:      | 2.4MB 9.8MB/s
[ec2-54-88-141-236.compute-1.amazonaws.com] out:     Complete output from command python setup.py egg_info:
[ec2-54-88-141-236.compute-1.amazonaws.com] out:     Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.35.tar.gz
[ec2-54-88-141-236.compute-1.amazonaws.com] out:     Extracting in /tmp/tmpHCWGqX
[ec2-54-88-141-236.compute-1.amazonaws.com] out:     Now working in /tmp/tmpHCWGqX/distribute-0.6.35
[ec2-54-88-141-236.compute-1.amazonaws.com] out:     Building a Distribute egg in /tmp/pip-lAdVKN-build
[ec2-54-88-141-236.compute-1.amazonaws.com] out:     Traceback (most recent call last):
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "setup.py", line 45, in <module>
[ec2-54-88-141-236.compute-1.amazonaws.com] out:         exec(init_file.read(), d)
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "<string>", line 8, in <module>
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "/tmp/tmpHCWGqX/distribute-0.6.35/setuptools/__init__.py", line 2, in <module>
[ec2-54-88-141-236.compute-1.amazonaws.com] out:         from setuptools.extension import Extension, Library
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "/tmp/tmpHCWGqX/distribute-0.6.35/setuptools/extension.py", line 5, in <module>
[ec2-54-88-141-236.compute-1.amazonaws.com] out:         from setuptools.dist import _get_unpatched
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "/tmp/tmpHCWGqX/distribute-0.6.35/setuptools/dist.py", line 6, in <module>
[ec2-54-88-141-236.compute-1.amazonaws.com] out:         from setuptools.command.install import install
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "/tmp/tmpHCWGqX/distribute-0.6.35/setuptools/command/__init__.py", line 8, in <module>
[ec2-54-88-141-236.compute-1.amazonaws.com] out:         from setuptools.command import install_scripts
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "/tmp/tmpHCWGqX/distribute-0.6.35/setuptools/command/install_scripts.py", line 3, in <module>
[ec2-54-88-141-236.compute-1.amazonaws.com] out:         from pkg_resources import Distribution, PathMetadata, ensure_directory
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "/tmp/tmpHCWGqX/distribute-0.6.35/pkg_resources.py", line 2825, in <module>
[ec2-54-88-141-236.compute-1.amazonaws.com] out:         add_activation_listener(lambda dist: dist.activate())
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "/tmp/tmpHCWGqX/distribute-0.6.35/pkg_resources.py", line 710, in subscribe
[ec2-54-88-141-236.compute-1.amazonaws.com] out:         callback(dist)
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "/tmp/tmpHCWGqX/distribute-0.6.35/pkg_resources.py", line 2825, in <lambda>
[ec2-54-88-141-236.compute-1.amazonaws.com] out:         add_activation_listener(lambda dist: dist.activate())
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "/tmp/tmpHCWGqX/distribute-0.6.35/pkg_resources.py", line 2257, in activate
[ec2-54-88-141-236.compute-1.amazonaws.com] out:         self.insert_on(path)
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "/tmp/tmpHCWGqX/distribute-0.6.35/pkg_resources.py", line 2358, in insert_on
[ec2-54-88-141-236.compute-1.amazonaws.com] out:         "with distribute. Found one at %s" % str(self.location))
[ec2-54-88-141-236.compute-1.amazonaws.com] out:     ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /usr/local/anaconda/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg
[ec2-54-88-141-236.compute-1.amazonaws.com] out:     /tmp/pip-lAdVKN-build/distribute-0.6.35-py2.7.egg
[ec2-54-88-141-236.compute-1.amazonaws.com] out:     Traceback (most recent call last):
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "<string>", line 1, in <module>
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "/tmp/pip-lAdVKN-build/setup.py", line 9, in <module>
[ec2-54-88-141-236.compute-1.amazonaws.com] out:         use_setuptools()
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "distribute_setup.py", line 152, in use_setuptools
[ec2-54-88-141-236.compute-1.amazonaws.com] out:         return _do_download(version, download_base, to_dir, download_delay)
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "distribute_setup.py", line 132, in _do_download
[ec2-54-88-141-236.compute-1.amazonaws.com] out:         _build_egg(egg, tarball, to_dir)
[ec2-54-88-141-236.compute-1.amazonaws.com] out:       File "distribute_setup.py", line 123, in _build_egg
[ec2-54-88-141-236.compute-1.amazonaws.com] out:         raise IOError('Could not build the egg.')
[ec2-54-88-141-236.compute-1.amazonaws.com] out:     IOError: Could not build the egg.
[ec2-54-88-141-236.compute-1.amazonaws.com] out:     
[ec2-54-88-141-236.compute-1.amazonaws.com] out:     ----------------------------------------
[ec2-54-88-141-236.compute-1.amazonaws.com] out: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-lAdVKN-build/
[ec2-54-88-141-236.compute-1.amazonaws.com] out: 

Fatal error: run() received nonzero return code 1 while executing!

Requested: /usr/local/anaconda/bin/pip install --upgrade https://bitbucket.org/james_taylor/bx-python/get/tip.tar.bz2
Executed: /bin/bash -i -c "/usr/local/anaconda/bin/pip install --upgrade https://bitbucket.org/james_taylor/bx-python/get/tip.tar.bz2"

Aborting.

Disconnecting from ec2-54-88-141-236.compute-1.amazonaws.com... done.
```

**Comment by chapmanb** [comment]
Sorry about the confusion. We have been moving away from the approach of installing everything to allowing customized installs. Sorry, the documentation does not reflect this and I updated it to suggest using the bcbio installer, which wraps CloudBioLinux, as a first pass if you want to bootstrap a system with a full set of tools for sequencing analysis:

https://github.com/chapmanb/cloudbiolinux#quick-start

Happy to provide more information to help, but hope this works for your needs.
