### ISSUE TITLE
Issues with installing dbscSNV

### ISSUE THREAD

**Issue by mmoisse** [chapmanb/cloudbiolinux#312]
While installing dbscSNV I get the following error ``non-zero exit status 141``

    + '[' '!' -f dbscSNV.txt.gz ']'
    ++ pwd
    + UNPACK_DIR=/software/local/share/bcbio/genomes/Hsapiens/hg38/txtmp/variation/tmp-unpack
    + mkdir -p /software/local/share/bcbio/genomes/Hsapiens/hg38/txtmp/variation/tmp-unpack
    + unzip -p dbscSNV1.1.zip 'dbscSNV*.chr1'
    + head -n1
    Traceback (most recent call last):
      File "/software/local/share/bcbio/anaconda/bin/bcbio_nextgen.py", line 221, in <module>
        install.upgrade_bcbio(kwargs["args"])
      File "/software/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
        upgrade_bcbio_data(args, REMOTES)
      File "/software/local/share/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 349, in upgrade_bcbio_data
        args.cores, ["ggd", "s3", "raw"])
      File "/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
        _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
      File "/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
        retrieve_fn(env, manager, gid, idx)
      File "/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 850, in _install_with_ggd
        ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
      File "/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
        recipe["recipe"]["full"]["recipe_type"], system_install)
      File "/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
        subprocess.check_output(["bash", run_file])
      File "/software/local/share/bcbio/anaconda/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/software/local/share/bcbio/anaconda/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['bash', '/software/local/share/bcbio/genomes/Hsapiens/hg38/txtmp/ggd-run.sh']' returned non-zero exit status 141.

**Comment by naumenko-sa** [comment]
Thanks for the fix! Please confirm if that works now! S

**Comment by mmoisse** [comment]
I just tested it and it works, but only for hg38 not for hg19

**Comment by mmoisse** [comment]
Applied the fix for hg19 and now it also works for hg19

**Comment by naumenko-sa** [comment]
Great! 
Could you please push a PR request for hg19 recipe? 
S

**Comment by naumenko-sa** [comment]
Thanks, @mmoisse !
still leaving it open as grch37 might also have a similar issue.
SN

**Comment by mmoisse** [comment]
It should be ok for GRCh37 since the recipe for hg19 is just a link to GRCh37 and I edited the GRCh37 recipe

https://github.com/chapmanb/cloudbiolinux/blob/dd9955757d4a6135a16e2584a3f84a2c750b7a68/ggd-recipes/hg19/dbscsnv.yaml#L1

**Comment by naumenko-sa** [comment]
ok, thanks!
